# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_title', models.CharField(max_length=200)),
                ('goods_subject', models.CharField(max_length=200)),
                ('goods_price', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='record_trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=200)),
                ('trade_subject', models.CharField(max_length=200)),
                ('trade_body', models.CharField(max_length=200)),
                ('trade_total_fee', models.CharField(max_length=200)),
            ],
        ),
    ]
