# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alipayModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_trade',
            name='trade_state',
            field=models.IntegerField(default=0),
        ),
    ]
